// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'App': string;
  'App-header': string;
  'App-link': string;
  'App-logo': string;
  'App-logo-spin': string;
  'borderBox': string;
  'button': string;
  'center': string;
  'contentBlock': string;
  'flexColumn': string;
  'hover': string;
  'icon': string;
  'inputBlock': string;
  'inputBlockFocusOff': string;
  'listItem': string;
  'mainPanel': string;
  'selectMessage': string;
  'selectedItem': string;
  'subPanel': string;
  'textHover': string;
}
export const cssExports: CssExports;
export default cssExports;
